  msg[0]:=
  'Sie gehören nicht zur Gruppe der Administratoren.'#10#13#10#13
  'Um aus jeder Anwendung ein PDF-Dokument zu erzeugen, verwendet PDFCreator einen Postscript Druckertreiber.'#13
  'Für die Installation eines Druckertreibers müssen Sie zur Gruppe der Administratoren gehören.'#13#13
  'Wenn Sie mit der Installation fortfahren, können Sie nur bereits erstellte Postscript-Dateien konvertieren.'#13#13
  'Soll das Setup fortgesetzt werden?';
  msg[1]:=
  'Es wurde eine alte Version '#39+GetInstalledVersionBeta+#39' gefunden!'#10#13 + 'Eine Aktualisierung auf die Version '#39+ExpandConstant('{#AppVersionStr}')+#39' ist möglich.'#10#13#10#13;
  msg[2]:=
  'Für dieses Update müssen Sie kein Mitglied einer Gruppe der Administratoren sein.'#10#13#10#13;
  msg[3]:=
  'Wenn ein Update durchgeführt werden soll, betätigen Sie die <OK> Taste,'#10#13
  'ansonsten brechen Sie die Installation ab und deinstallieren zuvor die alte Version.';
  msg[4]:=
  'Das Programm ist bereits installiert.'#10#13#10#13
  'Für eine Neuinstallation deinstallieren Sie zuvor das Programm.'#10#13#10#13
  'Die Installation wird abgebrochen.';
  msg[5]:=
  'Die installierte Version '#39+GetInstalledVersion+#39' ist aktueller, als diese Installationsversion ('+ExpandConstant('{#AppVersionStr}')+')!'#10#13#10#13
  'Für die Installation einer älteren Version, deinstallieren zuvor das Programm.'#10#13#10#13
  'Die Installation wird abgebrochen.';
  msg[6]:=
  'Das Programm wurde bereits installiert.'#10#13#10#13
  'Ein Update ist nicht möglich! Bitte deinstallieren Sie erst das Programm.'#10#13#10#13
  'Die Installation wird abgebrochen.';
  msg[7]:=
  'Das Programm <PDFCreator.exe> wird gerade verwendet.'#10#13#10#13
  'Bitte beenden Sie das Programm erst.'#10#13#10#13;
  msg[8]:=
  'Das Programm <Transtool.exe> wird gerade verwendet.'#10#13#10#13
  'Bitte beenden Sie das Programm erst.'#10#13#10#13;
  msg[9]:=
  'Das Programm <PDFSpooler.exe> wird gerade verwendet.'#10#13#10#13
  'Bitte warten Sie bis alle Druckaufträge abgearbeitet wurden.'#10#13#10#13;
  msg[10]:=
  'Das Programm <UnInst.exe> wird gerade verwendet.'#10#13#10#13
  'Bitte beenden Sie die Deinstallation erst.'#10#13#10#13;
  msg[11]:=
  'Es wurde eine alte Version '#39+GetInstalledVersionBeta+#39' gefunden!'#10#13#10#13
  'Eine Aktualisierung auf die Version '#39+ExpandConstant('{#AppVersionStr}')+#39' ist nicht möglich.'#10#13#10#13
  'Bitte deinstallieren Sie das Programm zuerst.';
