Name: dutch;        MessagesFile: compiler:Languages\Dutch.isl
Name: english;      MessagesFile: compiler:Default.isl
Name: french;       MessagesFile: compiler:Languages\French.isl
Name: german;       MessagesFile: compiler:Languages\German.isl; LicenseFile: .\License\Program license - german.rtf
Name: italian;      MessagesFile: compiler:Languages\Italian.isl
Name: romanian;     MessagesFile: Romanian.isl
Name: russian;      MessagesFile: compiler:Languages\Russian.isl
Name: slovak;       MessagesFile: Slovak.isl
Name: slovenian;    MessagesFile: compiler:Languages\Slovenian.isl
