; english must be the first entry
Name: english;            MessagesFile: compiler:Default.isl
;Name: basque;             MessagesFile: compiler:Languages\Basque.isl
;Name: catalan;            MessagesFile: compiler:Languages\Catalan.isl
;Name: czech;              MessagesFile: compiler:Languages\Czech.isl
;Name: chinese_simplified; MessagesFile: Innosetup languages files\ChineseSimp-12-5.1.11.isl
;Name: chinese_traditional; MessagesFile: Innosetup languages files\ChineseTrad-2-5.1.11.isl
;Name: danish;              MessagesFile: compiler:Languages\Danish.isl
;Name: dutch;              MessagesFile: compiler:Languages\Dutch.isl
;Name: estonian;           MessagesFile: Innosetup languages files\Estonian-2-5.1.0.isl
;Name: finnish;            MessagesFile: compiler:Languages\Finnish.isl
Name: french;             MessagesFile: compiler:Languages\French.isl
;Name: galician;           MessagesFile: Innosetup languages files\Galician-2-5.1.11.isl
Name: german;             MessagesFile: compiler:Languages\German.isl; LicenseFile: .\License\Program license - german.rtf
;Name: greek;              MessagesFile: Innosetup languages files\Greek-4-5.1.11.isl
;Name: hebrew;             MessagesFile: compiler:Languages\Hebrew.isl
;Name: hungarian;          MessagesFile: compiler:Languages\Hungarian.isl
;Name: indonesian;         MessagesFile: Innosetup languages files\Indonesian-5.1.11.isl
;Name: italian;            MessagesFile: compiler:Languages\Italian.isl
;Name: japanese;           MessagesFile: Innosetup languages files\Japanese-5-5.1.11.isl
;Name: korean;             MessagesFile: Innosetup languages files\Korean-5-5.1.11.isl
;Name: lithuanian;         MessagesFile: Innosetup languages files\Lithuanian-4-5.1.11.isl
;Name: norwegian_bokmal;   MessagesFile: compiler:Languages\Norwegian.isl
;Name: polish;             MessagesFile: compiler:Languages\Polish.isl
;Name: portuguese_br;      MessagesFile: compiler:Languages\BrazilianPortuguese.isl
;Name: romanian;           MessagesFile: Innosetup languages files\Romanian-6-5.1.11.isl
;Name: russian;            MessagesFile: compiler:Languages\Russian.isl
;Name: slovak;             MessagesFile: compiler:Languages\Slovak.isl
;Name: slovenian;          MessagesFile: compiler:Languages\Slovenian.isl
;Name: spanish;            MessagesFile: compiler:Languages\Spanish.isl
;Name: swedish;            MessagesFile: Innosetup languages files\Swedish-10-5.1.12.isl
;Name: turkish;            MessagesFile: Innosetup languages files\Turkish-3-5.1.11.isl
;Name: ukrainian;          MessagesFile: Innosetup languages files\Ukrainian-5-5.1.0.isl
;Name: valencian;          MessagesFile: Innosetup languages files\Valencian-1-5.1.11.isl
