; english must be the first entry
Name: english;            MessagesFile: compiler:Default.isl
Name: catalan;            MessagesFile: compiler:Languages\Catalan.isl
Name: chinese_simplified; MessagesFile: Innosetup languages files\ChineseSimp-11-5.1.0.isl
Name: dutch;              MessagesFile: compiler:Languages\Dutch.isl
Name: french;             MessagesFile: compiler:Languages\French.isl
Name: german;             MessagesFile: compiler:Languages\German.isl; LicenseFile: .\License\Program license - german.rtf
Name: indonesian;         MessagesFile: Innosetup languages files\Indonesian-5.1.0.isl
Name: italian;            MessagesFile: compiler:Languages\Italian.isl
Name: lithuanian;         MessagesFile: Innosetup languages files\Lithuanian-4-5.1.0.isl
Name: romanian;           MessagesFile: Innosetup languages files\Romanian-5-5.1.0.isl
Name: russian;            MessagesFile: compiler:Languages\Russian.isl
Name: slovak;             MessagesFile: compiler:Languages\Slovak.isl
Name: slovenian;          MessagesFile: compiler:Languages\Slovenian.isl
