Name: czech;     MessagesFile: compiler:Languages\czech.isl
Name: english;   MessagesFile: compiler:Default.isl
Name: german;    MessagesFile: compiler:Languages\German.isl; LicenseFile: .\License\Program license - german.rtf
Name: slovak;    MessagesFile: Slovak.isl
Name: dutch;     MessagesFile: compiler:Languages\Dutch.isl
Name: italian;   MessagesFile: compiler:Languages\Italian.isl
Name: hungarian; MessagesFile: compiler:Languages\hungarian.isl
Name: french;    MessagesFile: compiler:Languages\french.isl
Name: slovensko; MessagesFile: compiler:Languages\Slovenian.isl
Name: spanish;   MessagesFile: Spanish.isl
Name: greek;     MessagesFile: Greek.isl
