Name: desktopicon; Description: &Desktopsymbol anlegen; GroupDescription: Zusätzliche Symbole:; Languages: German
Name: desktopicon\common; Description: Für &alle Benutzer; GroupDescription: Zusätzliche Symbole:; Flags: exclusive; Languages: German
Name: desktopicon\user; Description: Nur für den angemeldeten &Benutzer; GroupDescription: Zusätzliche Symbole:; Flags: exclusive unchecked; Languages: German
Name: quicklaunchicon; Description: Erzeuge eine Symbol in der &Schnellzugriffsleiste; GroupDescription: Zusätzliche Symbole:; Flags: unchecked; Check: IExplorerVersionGreater3; Languages: German

#Ifdef GhostscriptVersion
Name: ghostscript; Description: Installiere {#License} &Ghostscript Version {#GhostscriptVersion}; GroupDescription: Andere Aufgaben:; Flags: exclusive; Languages: German
#ENDIF

Name: fileassoc; Description: &Verknüpfe PDFCreator mit der Dateierweiterung .ps; GroupDescription: Andere Aufgaben:; Flags: unchecked; Languages: German
Name: winexplorer; Description: Erzeuge einen &Eintrag im Windows-Explorer Kontextmenü; GroupDescription: Andere Aufgaben:; Languages: German
