Name: czech;        MessagesFile: compiler:Languages\Czech.isl
Name: english;      MessagesFile: compiler:Default.isl
Name: french;       MessagesFile: compiler:Languages\French.isl
Name: german;       MessagesFile: compiler:Languages\German.isl; LicenseFile: .\License\Program license - german.rtf
Name: greek;        MessagesFile: Greek.isl
Name: hungarian;    MessagesFile: compiler:Languages\Hungarian.isl
Name: icelandic;    MessagesFile: Icelandic.isl
Name: indonesian;   MessagesFile: Indonesian.isl
Name: norwegian;    MessagesFile: compiler:Languages\Norwegian.isl
Name: polish;       MessagesFile: compiler:Languages\Polish.isl
Name: portuguesebr; MessagesFile: compiler:Languages\BrazilianPortuguese.isl
Name: portuguesept; MessagesFile: compiler:Languages\Portuguese.isl
Name: romanian;     MessagesFile: Romanian.isl
Name: russian;      MessagesFile: compiler:Languages\Russian.isl
Name: slovak;       MessagesFile: Slovak.isl
Name: slovensko;    MessagesFile: compiler:Languages\Slovenian.isl