Name: czech;     MessagesFile: czech.isl
Name: english;   MessagesFile: compiler:Default.isl
Name: german;    MessagesFile: German.isl; LicenseFile: .\License\Program license - german.rtf
Name: slovak;    MessagesFile: Slovak-4.2.2.isl
Name: dutch;     MessagesFile: compiler:Languages\Dutch.isl
Name: italian;   MessagesFile: Italian-3-4.2.1.isl
Name: hungarian; MessagesFile: hungarian.isl
Name: french;    MessagesFile: compiler:Languages\french.isl
Name: slovensko; MessagesFile: compiler:Languages\Slovenian.isl
Name: spanish;   MessagesFile: compiler:Languages\Spanish.isl
