Name: chinese_simplified; MessagesFile: ChineseSimp-11-5.1.0.isl
Name: dutch;              MessagesFile: compiler:Languages\Dutch.isl
Name: english;            MessagesFile: compiler:Default.isl
Name: french;             MessagesFile: compiler:Languages\French.isl
Name: german;             MessagesFile: compiler:Languages\German.isl; LicenseFile: .\License\Program license - german.rtf
Name: indonesian;         MessagesFile: Indonesian-5.1.0.isl
Name: italian;            MessagesFile: compiler:Languages\Italian.isl
Name: romanian;           MessagesFile: Romanian-5-5.1.0.isl
Name: russian;            MessagesFile: compiler:Languages\Russian.isl
Name: slovak;             MessagesFile: compiler:Languages\Slovak.isl
Name: slovenian;          MessagesFile: compiler:Languages\Slovenian.isl
