Echo j | Del  ..\PDFCreator\*.exe
Echo j | Del  ..\PDFCreator\*.obj
Echo j | Del  ..\PDFSpooler\*.exe
Echo j | Del  ..\PDFSpooler\*.obj
Echo j | Del  ..\Transtool\*.exe
Echo j | Del  ..\Transtool\*.
Echo j | Del  ..\DeveloperTool\*.exe
Echo j | Del  ..\DeveloperTool\*.obj
Echo j | Del  ..\Setup\Installation\PDFCreator*.exe